import { Injectable } from '@angular/core';
import { Store } from '../models/menu.model';

@Injectable({ providedIn: 'root' })
export class MenuDataService {
  readonly stores: Store[] = [
    {
      id: 'daily',
      name: '達利早餐',
      badge: '連鎖品牌',
      address: '新北市三重區光復路一段68巷7號（總部）',
      hours: '06:00 - 14:00',
      phone: '(02) 2228-9570',
      website: 'https://dailybreakfast.com.tw',
      menu: {
        '🥚 蛋餅系列': [
          { name: '原味蛋餅', price: 35 },
          { name: '起士蛋餅', price: 45 },
          { name: '玉米蛋餅', price: 45 },
          { name: '火腿蛋餅', price: 40 },
          { name: '蔬菜蛋餅', price: 45 },
          { name: '鮪魚蛋餅', price: 55 },
          { name: '里肌豬排蛋餅', price: 60, popular: true },
          { name: '拉絲蛋餅', price: 55, popular: true },
          { name: '薯餅起士蛋餅', price: 65 },
          { name: '厚蛋蔥香蛋餅', price: 55 },
        ],
        '🍔 職人烘焙堡': [
          { name: '漢堡肉堡', price: 60 },
          { name: '麥香雞堡', price: 60 },
          { name: '里肌豬排堡', price: 65 },
          { name: '蕈菇嫩蛋堡', price: 65 },
          { name: '檸檬優格魚排堡', price: 70 },
          { name: '經典牛肉起士堡', price: 75, popular: true },
          { name: '檸檬優格雞胸堡', price: 75 },
          { name: '蜜焰雞胸堡', price: 75 },
          { name: '蜜焰卡啦雞堡', price: 80 },
          { name: 'BBQ雞腿排堡', price: 85, popular: true },
          { name: '胡麻豬排堡', price: 85 },
          { name: '黃金厚炸豬排堡', price: 85 },
          { name: '經典美式厚牛堡', price: 95 },
        ],
        '🥐 鹽可頌 / 黑麥歐包': [
          { name: '地瓜火腿鹽可頌', price: 65 },
          { name: '蕈菇嫩蛋鹽可頌', price: 75 },
          { name: '鮮蝦蛋沙拉鹽可頌', price: 95, popular: true },
          { name: '地瓜火腿黑麥歐包', price: 65 },
          { name: '蕈菇嫩蛋黑麥歐包', price: 75 },
          { name: '鮮蝦蛋沙拉黑麥歐包', price: 95 },
          { name: '黑麥歐包套餐', price: 145 },
        ],
        '🥪 吐司系列': [
          { name: '方火腿吐司', price: 45 },
          { name: '漢堡肉吐司', price: 45 },
          { name: '麥香雞吐司', price: 45 },
          { name: '地瓜素鬆吐司', price: 45 },
          { name: '鮮蔬嫩蛋吐司', price: 50 },
          { name: '甜鮪魚吐司', price: 50 },
          { name: '里肌豬排吐司', price: 55 },
          { name: '經典蛋沙拉吐司', price: 55, popular: true },
          { name: '蔥蛋里肌吐司', price: 65 },
          { name: '檸檬優格魚排吐司', price: 65 },
          { name: '檸檬優格雞胸吐司', price: 70 },
          { name: '蜜焰香煎雞胸吐司', price: 70 },
          { name: '總匯三明治', price: 70 },
          { name: '鮪魚蛋沙拉總匯', price: 70 },
          { name: '里肌總匯', price: 75 },
          { name: 'BBQ雞腿排總匯', price: 85 },
          { name: '花生蜜焰卡啦雞總匯', price: 85 },
        ],
        '🍝 鐵板麵 / 拌麵': [
          { name: '蘑菇鐵板麵', price: 60, popular: true },
          { name: '黑胡椒鐵板麵', price: 60, popular: true },
          { name: '宮保雞丁鐵板麵', price: 70 },
          { name: '達利炒麵', price: 75 },
          { name: '眷村蝦米蔥拌麵', price: 85 },
          { name: '蘑菇鐵板麵COMBO', price: 95 },
          { name: '黑胡椒鐵板麵COMBO', price: 95 },
          { name: '宮保雞丁鐵板麵COMBO', price: 105 },
          { name: '眷村麻醬鐵板麵（含蛋）', price: 70 },
          { name: '川味麻辣鐵板麵（含蛋）', price: 70 },
        ],
        '🍜 烏龍系列': [
          { name: '慢煮百菇炒烏龍', price: 120 },
          { name: '招牌和風炒烏龍', price: 130, popular: true },
          { name: '家傳椒麻炒烏龍', price: 140, popular: true },
          { name: '辣味噌炒烏龍', price: 145 },
          { name: '慢煮百菇湯烏龍', price: 135 },
          { name: '招牌和風湯烏龍', price: 145 },
          { name: '日式味噌湯烏龍', price: 155 },
        ],
        '🍝 義大利麵': [
          { name: '經典番茄肉醬義大利麵', price: 130 },
          { name: '義式青醬蕈菇義大利麵', price: 150 },
          { name: '奶油白醬蕈菇義大利麵', price: 150 },
          { name: '青醬蕈菇雞胸義大利麵', price: 165 },
          { name: '奶油蕈菇香煎雞腿義大利麵', price: 185 },
        ],
        '🍳 總匯套餐': [
          { name: 'BBQ雞腿排總匯套餐', price: 145, popular: true },
          { name: '里肌總匯套餐', price: 125 },
          { name: '經典法式雞腿集合', price: 185 },
        ],
        '🥗 水耕沙拉': [
          { name: '蛋沙拉水耕沙拉', price: 150 },
          { name: '牧場蕈菇水耕沙拉', price: 160 },
          { name: '嫩煎雞胸水耕沙拉', price: 165, popular: true },
          { name: '舒肥雞水耕沙拉', price: 185 },
          { name: '燻鮭魚水耕沙拉', price: 185 },
        ],
        '🌯 墨西哥捲': [
          { name: '地瓜素鬆鮮蔬捲', price: 75 },
          { name: '檸檬優格雞胸捲', price: 95, popular: true },
          { name: '蜜焰卡啦雞捲', price: 95 },
          { name: '胡麻炸豬排捲', price: 95 },
          { name: '黃金厚切炸豬排捲', price: 95 },
        ],
        '🍞 麵包 / 鬆餅 / 厚片': [
          { name: '美味草莓薄片', price: 30 },
          { name: '濃巧克力薄片', price: 30 },
          { name: '撲鼻香蒜薄片', price: 30 },
          { name: '香濃奶酥薄片', price: 30 },
          { name: '顆粒花生薄片', price: 30 },
          { name: '奶油餐包', price: 45 },
          { name: '蜂蜜法式吐司', price: 55 },
          { name: '鹽可頌', price: 55 },
          { name: '黑麥歐包', price: 55 },
          { name: '美味草莓厚片', price: 55 },
          { name: '濃巧克力厚片', price: 55 },
          { name: '撲鼻香蒜厚片', price: 55 },
          { name: '香濃奶酥厚片', price: 55 },
          { name: '顆粒花生厚片', price: 55 },
          { name: '英式圓鬆餅', price: 55 },
          { name: '晨光厚片', price: 60 },
          { name: 'Oreo巧克力煉乳厚片', price: 70 },
        ],
        '🥟 小點': [
          { name: '小熱狗', price: 25 },
          { name: '薯餅', price: 30 },
          { name: '鮮奶炒蛋', price: 45 },
          { name: '麥克雞塊', price: 50 },
          { name: '地瓜球', price: 50 },
          { name: '酥炸脆薯', price: 55 },
          { name: '薯餅起士蛋塔', price: 55 },
          { name: '蜜焰雞塊', price: 55 },
          { name: '檸檬優格雞柳', price: 65 },
        ],
        '☕ 飲料 / 咖啡': [
          { name: '達利奶茶（大）', price: 40, popular: true },
          { name: '達利嚴選紅茶', price: 25 },
          { name: '無糖綠茶（大）', price: 30 },
          { name: '鮮檸檬紅茶（大）', price: 38 },
          { name: '豆漿（大）', price: 25 },
          { name: '豆奶紅茶（大）', price: 38 },
          { name: '鮮奶茶（大）', price: 50 },
          { name: '花園奶茶（大）', price: 55 },
          { name: '香蜜鮮奶茶（中）', price: 55 },
          { name: '花園鮮奶茶（大）', price: 60 },
          { name: '經典可可（大）', price: 65 },
          { name: '鮮奶（中）', price: 55 },
          { name: '蜂釀牛奶（中）', price: 65 },
          { name: '天然柳橙原汁（中）', price: 85 },
          { name: '奇異果綜合汁（中）', price: 85 },
          { name: '美式咖啡', price: 50 },
          { name: '春蜜美式（中）', price: 55 },
          { name: '特調咖啡（大）', price: 70 },
          { name: '招牌拿鐵（大）', price: 70, popular: true },
          { name: '焦糖拿鐵（大）', price: 75 },
          { name: '春蜜拿鐵（中）', price: 75 },
          { name: '榛果拿鐵（大）', price: 90 },
        ],
      },
    },
    {
      id: 'mwd',
      name: '麥味登',
      badge: '五股中興店',
      address: '新北市五股區中興路四段48巷1號1樓',
      hours: '06:30 - 15:30',
      phone: '+886922511853',
      menu: {
        '✨ 新品上市': [
          { name: '香菜炸餃', price: 70, popular: true },
          { name: '原塊嫩雞花椰菜米', price: 165, popular: true },
          { name: '酸菜花生滿分堡', price: 80 },
        ],
        '🍔 漢堡系列': [
          { name: '香雞漢堡', price: 45 },
          { name: '豬肉漢堡', price: 50 },
          { name: '鮪魚漢堡', price: 55 },
          { name: '燻雞漢堡', price: 55 },
          { name: '培根漢堡', price: 55 },
          { name: '黑胡椒豬里肌漢堡', price: 60 },
          { name: '卡滋雞腿漢堡', price: 85, popular: true },
          { name: '超厚雞肉起司漢堡', price: 85 },
          { name: '超厚牛肉起司漢堡', price: 90, popular: true },
          { name: '原塊嫩雞起司漢堡', price: 105 },
        ],
        '🧇 滿分堡系列': [
          { name: '歐姆蛋滿分堡', price: 55 },
          { name: '火腿薯餅滿分堡', price: 55 },
          { name: '豬肉起司滿分堡', price: 60, popular: true },
          { name: '黑胡椒豬里肌蛋滿分堡', price: 70 },
          { name: '鮪魚蛋滿分堡', price: 70 },
          { name: '超厚雞肉起司滿分堡', price: 75 },
          { name: '花生厚牛起司滿分堡', price: 90 },
          { name: '原塊嫩雞起司滿分堡', price: 95, popular: true },
          { name: '酸菜花生滿分堡', price: 80 },
        ],
        '🥐 可頌 / 丹麥': [
          { name: '香雞可頌', price: 60 },
          { name: '鮮蛋沙拉可頌', price: 70 },
          { name: '鮪魚可頌', price: 75 },
          { name: '燻雞可頌', price: 75, popular: true },
          { name: '培根可頌', price: 75 },
          { name: '黑胡椒豬里肌可頌', price: 85 },
          { name: '超厚雞肉起司可頌', price: 100 },
          { name: '卡滋雞腿可頌', price: 100 },
          { name: '超厚牛肉起司可頌', price: 105 },
          { name: '原塊嫩雞起司可頌', price: 120 },
          { name: '鮪魚丹麥麵包', price: 75 },
          { name: '燻雞丹麥麵包', price: 75 },
          { name: '培根丹麥麵包', price: 75 },
          { name: '黑胡椒豬里肌丹麥麵包', price: 85 },
          { name: '超厚雞肉起司丹麥麵包', price: 100 },
          { name: '卡滋雞腿丹麥麵包', price: 100 },
          { name: '超厚牛肉起司丹麥麵包', price: 105 },
          { name: '原塊嫩雞起司丹麥', price: 120 },
        ],
        '🥚 蛋餅系列': [
          { name: '原味蛋餅', price: 40 },
          { name: '手工蔥抓蛋餅', price: 55, popular: true },
          { name: '鮪魚蛋餅', price: 60 },
          { name: '薯餅蛋餅', price: 60 },
          { name: '培根蛋餅', price: 70 },
          { name: '豬里肌蛋餅', price: 70 },
          { name: '德腸握蛋捲餅', price: 85 },
          { name: '豬里肌握蛋捲餅', price: 85, popular: true },
          { name: '培根握蛋捲餅', price: 85 },
          { name: '燻雞握蛋捲餅', price: 85 },
          { name: '鮪魚握蛋捲餅', price: 85 },
          { name: '起司雙重奏握蛋捲餅', price: 85 },
        ],
        '🍝 鐵板麵系列': [
          { name: '蘑菇鐵板麵', price: 60, popular: true },
          { name: '黑胡椒鐵板麵', price: 60, popular: true },
          { name: '眷村麻醬鐵板麵 (含蛋)', price: 70 },
          { name: '川味麻辣鐵板麵 (含蛋)', price: 70 },
        ],
        '🥟 點心系列': [
          { name: '菜脯蛋', price: 35 },
          { name: '法國吐司', price: 45 },
          { name: '雞塊', price: 50 },
          { name: '黃金脆薯', price: 50 },
          { name: '四角薯餅', price: 50 },
          { name: '歐姆蛋', price: 50 },
          { name: '香檸雞柳', price: 50 },
          { name: '美式鬆餅', price: 50 },
          { name: '黃金泡菜酥炸餃', price: 55, popular: true },
          { name: '薯餅蛋塔', price: 55, popular: true },
          { name: '台灣番薯 (2顆)', price: 55 },
          { name: '黃金泡菜蘿蔔糕', price: 60 },
          { name: '椒麻雞塊', price: 60 },
          { name: '時蔬嫩蛋', price: 60 },
          { name: '嫩煎雞腿排', price: 80 },
          { name: '原塊嫩雞 (單片)', price: 80 },
          { name: '唐揚雞塊', price: 85 },
          { name: '酥炸杏鮑菇', price: 85 },
          { name: '香菜炸餃 (10顆)', price: 70 },
        ],
        '🍳 早午餐特餐': [
          { name: '美式鬆餅特餐', price: 140 },
          { name: '法式特餐', price: 150, popular: true },
          { name: '幸福特餐', price: 150 },
          { name: '樂活特餐', price: 160 },
          { name: '蘿勒燻雞三明治特餐', price: 165 },
          { name: '花生布里歐特餐', price: 165 },
          { name: '法式蘿勒鮪魚特餐', price: 170 },
          { name: '台式特餐', price: 170 },
          { name: '好食嫩雞餐', price: 205 },
          { name: '泰式卡滋脆雞特餐', price: 205 },
          { name: '威爾遜嫩煎腿排可頌餐', price: 210 },
        ],
        '👨‍🍳 主廚系列': [
          { name: '奶油培根義大利麵', price: 145 },
          { name: '青醬雞肉義大利麵', price: 160 },
          { name: '青醬蘑菇義大利麵', price: 160 },
          { name: '茄汁原塊嫩雞義大利麵', price: 170 },
          { name: '茄汁德腸燉飯', price: 170 },
          { name: '蘿勒燻雞燉飯', price: 170 },
          { name: '咖哩杏鮑菇燉飯', price: 170 },
          { name: '咖哩唐揚雞蛋包飯', price: 195 },
          { name: '西式紅酒牛肉飯', price: 250 },
        ],
        '🥗 輕食尚餐': [
          { name: '紫米時蔬嫩雞飯', price: 170 },
          { name: '優蛋白蛋捲餐', price: 180 },
          { name: '地瓜雞肉餐', price: 190, popular: true },
          { name: '時蔬豆皮蛋餅特餐', price: 190 },
          { name: '原塊嫩雞花椰菜米', price: 165 },
        ],
        '☕ 咖啡飲品': [
          { name: '熱美式咖啡', price: 55 },
          { name: '冰美式咖啡', price: 55 },
          { name: '熱拿鐵咖啡', price: 65, popular: true },
          { name: '冰拿鐵咖啡', price: 65 },
          { name: '熱焦糖拿鐵咖啡', price: 75 },
          { name: '冰焦糖拿鐵咖啡', price: 75 },
          { name: '熱榛果拿鐵咖啡', price: 75 },
          { name: '冰榛果拿鐵咖啡', price: 75 },
          { name: '萊姆檸淬咖啡 (冰)(L)', price: 85 },
        ],
        '🧋 飲料': [
          { name: '冰紅茶 (大)', price: 35 },
          { name: '熱紅茶 (大)', price: 35 },
          { name: '冰綠茶 (大)', price: 35 },
          { name: '豆漿紅茶 (L)', price: 35 },
          { name: '無糖豆漿 (L)', price: 35 },
          { name: '冰奶茶 (大)', price: 40 },
          { name: '熱奶茶 (大)', price: 40 },
          { name: '冰紅茶 (特大)', price: 40 },
          { name: '熱紅茶 (特大)', price: 40 },
          { name: '冰綠茶 (特大)', price: 40 },
          { name: '豆漿紅茶 (XL)', price: 40 },
          { name: '無糖豆漿 (XL)', price: 40 },
          { name: '冰奶茶 (特大)', price: 45 },
          { name: '熱奶茶 (特大)', price: 45 },
          { name: '冰紅茶拿鐵', price: 45 },
          { name: '熱紅茶拿鐵', price: 45 },
          { name: '手熬冬瓜茶 (XL)', price: 50 },
          { name: '冰可可牛乳', price: 50 },
          { name: '熱可可牛乳', price: 50 },
          { name: '冰山藥薏仁', price: 50 },
          { name: '熱山藥薏仁', price: 50 },
          { name: '冰紐西蘭牛奶', price: 55 },
          { name: '熱紐西蘭牛奶', price: 55 },
          { name: '夏威夷冰茶 (XL)', price: 60 },
          { name: '熱帶水果茶 (XL)', price: 60 },
          { name: '萊姆蜜紅茶 (XL)', price: 60 },
          { name: '鮮檸冬瓜茶 (XL)', price: 60 },
          { name: '黑糖方Q撞奶 (冰)(L)', price: 80 },
          { name: '紅豆斑蘭方Q紅茶', price: 55 },
        ],
        '🍲 湯品': [
          { name: '奶油玉米濃湯', price: 40 },
          { name: '巧達濃湯', price: 55 },
        ],
      },
    },
    {
      id: 'qburger',
      name: 'Q Burger',
      badge: '饗樂餐飲',
      address: '全台超過350家門市',
      hours: '06:00 - 14:00（依門市為準）',
      website: 'https://www.qburger.com.tw',
      menu: {
        '🍔 芝麻漢堡系列': [
          { name: '卡啦雞腿堡', price: 75, popular: true },
          { name: '花生熔岩卡啦雞腿堡', price: 85 },
          { name: '蜜汁嫩雞腿堡', price: 80 },
          { name: '嫩脆雞胸堡', price: 70 },
          { name: '阿拉斯加鱈魚堡', price: 75 },
          { name: '經典牛肉起士堡', price: 95, popular: true },
          { name: '牛肉起士堡', price: 75 },
          { name: '里肌豬排堡', price: 65 },
          { name: '三杯杏鮑菇雞堡', price: 90 },
          { name: '糖醋脆雞漢堡', price: 85 },
        ],
        '🥪 吐司系列': [
          { name: '100%肉鬆花生蛋吐司', price: 50, popular: true },
          { name: '培根蛋吐司', price: 45 },
          { name: '鮪魚吐司', price: 55 },
          { name: '經典火腿蛋吐司', price: 40 },
          { name: '里肌豬排吐司', price: 55 },
          { name: '燒肉蛋吐司', price: 60 },
          { name: '燒肉乳酪蛋吐司', price: 70 },
          { name: '嫩脆雞胸吐司', price: 70 },
          { name: '薯餅起士吐司', price: 55 },
          { name: '鮮蔬蕃茄起士吐司', price: 55 },
          { name: '鮮蔬馬鈴薯沙拉吐司', price: 55 },
          { name: '里肌豬排總匯', price: 85 },
          { name: '塔香鹹豬肉蛋吐司', price: 65 },
          { name: '巧克力吐司', price: 30 },
          { name: '花生吐司', price: 30 },
          { name: '草莓吐司', price: 30 },
          { name: '奶油吐司', price: 30 },
          { name: '椰香吐司', price: 30 },
        ],
        '🥐 可朗芙系列': [
          { name: '起士嫩蛋可朗芙', price: 55, popular: true },
          { name: '鮪魚玉米可朗芙', price: 55 },
          { name: '蜂蜜芥末卡啦雞可朗芙', price: 80 },
          { name: '蜂蜜可朗芙', price: 50 },
          { name: '草莓煉乳可朗芙', price: 55 },
          { name: '雙重巧克可朗芙', price: 55 },
          { name: '香蘋煉乳可朗芙', price: 55 },
          { name: '花醬可朗芙', price: 50 },
          { name: '經典可朗芙', price: 45 },
          { name: '芋見可朗芙', price: 75 },
        ],
        '🥚 蛋餅 ＆ 蔥抓餅': [
          { name: '里肌豬排蛋餅', price: 55, popular: true },
          { name: '里肌豬排蔥抓餅', price: 65 },
          { name: '100%肉鬆蛋餅', price: 50 },
          { name: '培根蛋餅', price: 45 },
          { name: '鮪魚蛋餅', price: 50 },
          { name: '怪怪總匯蛋餅', price: 60 },
          { name: '玉米蛋餅', price: 40 },
          { name: '九層塔蛋餅', price: 40 },
          { name: '原味蔥抓餅', price: 45 },
          { name: '塔香鹹豬肉蛋餅', price: 65 },
          { name: '三杯杏鮑菇蛋餅', price: 65 },
        ],
        '🌯 墨西哥捲餅': [
          { name: '嫩脆雞胸墨西哥捲', price: 85, popular: true },
          { name: '卡啦雞腿墨西哥捲', price: 85 },
          { name: '蜜汁嫩雞腿墨西哥捲', price: 85 },
          { name: '德式香腸墨西哥捲', price: 75 },
          { name: '田園蔬菜墨西哥捲', price: 65 },
        ],
        '🍝 炒泡麵 ＆ 鐵板麵': [
          { name: '招牌炒泡麵', price: 75, popular: true },
          { name: '椒麻炒泡麵', price: 80, popular: true },
          { name: '黑胡椒鐵板麵', price: 65 },
          { name: '蘑菇鐵板麵', price: 65 },
          { name: '沙茶鐵板麵', price: 65 },
          { name: '招牌炒泡麵組合餐（含里肌豬排+蛋）', price: 115 },
          { name: '椒麻炒泡麵組合餐（含里肌豬排+蛋）', price: 120 },
          { name: '黑胡椒鐵板麵組合餐（含里肌豬排+蛋）', price: 110 },
          { name: '蘑菇鐵板麵組合餐（含里肌豬排+蛋）', price: 110 },
          { name: '沙茶鐵板麵組合餐（含里肌豬排+蛋）', price: 110 },
          { name: '三杯杏鮑菇鐵板麵', price: 70 },
          { name: '三杯杏鮑菇鐵板麵組合餐', price: 130 },
        ],
        '🍜 鍋燒麵': [
          { name: '里肌豬排鍋燒麵', price: 95, popular: true },
          { name: '沙茶里肌豬排鍋燒麵', price: 100 },
        ],
        '🍝 義大利麵': [
          { name: '奶香培根義大利麵', price: 100 },
          { name: '奶香鮪魚義大利麵', price: 100 },
          { name: '拿坡里蕃茄德腸乳酪義大利麵', price: 110 },
        ],
        '🥐 起士軟法': [
          { name: '鮪魚起士軟法', price: 65 },
          { name: '嫩脆雞胸起士軟法', price: 75, popular: true },
          { name: '阿拉斯加鱈魚起士軟法', price: 75 },
        ],
        '🥗 輕食 / 沙拉': [
          { name: '香煎嫩雞大沙拉', price: 100 },
          { name: '香蘋鮮蔬沙拉', price: 60 },
          { name: '鮮蔬沙拉', price: 50 },
          { name: '蜜汁烤雞腿嫩炒蛋餐', price: 150 },
          { name: '菲力雞嫩炒蛋餐', price: 150 },
        ],
        '🍳 經典盤餐': [
          { name: '中式組合餐（蘿蔔糕＋煎餃＋九層塔煎蛋）', price: 90 },
          { name: '里肌豬總匯盤餐', price: 130 },
          { name: '鮪魚玉米可朗芙盤餐', price: 130 },
          { name: '蜂蜜芥末卡啦雞可朗芙盤餐', price: 160 },
          { name: 'QB 經典大滿足', price: 165 },
          { name: '芋見肉鬆厚片', price: 55 },
          { name: '芋見乳酪烤餅', price: 65 },
        ],
        '🍟 點心炸物': [
          { name: '鹹酥雞', price: 60, popular: true },
          { name: '九層塔鹹酥雞', price: 65 },
          { name: '洋釀脆雞球', price: 55, popular: true },
          { name: '手工甜不辣', price: 50 },
          { name: '鹹酥雞三拼', price: 99 },
          { name: '台農57號地瓜薯', price: 45 },
          { name: '台雞搭薯薯（鹽酥雞+地瓜薯）', price: 60 },
          { name: 'QQ地瓜球', price: 40 },
          { name: '薯餅', price: 30 },
          { name: '薯餅起士蛋塔', price: 55 },
          { name: '熱狗', price: 35 },
          { name: '德式香腸', price: 45 },
          { name: '麥克雞塊（4塊）', price: 45 },
          { name: '金牌蘿蔔糕', price: 45 },
          { name: '經典香蔥脆薯', price: 50 },
          { name: '巧達玉米濃湯', price: 45 },
        ],
        '🧇 烤餅': [
          { name: '蜜香奶油烤餅', price: 40 },
          { name: '花生乳酪烤餅', price: 50 },
          { name: '瑪格麗特烤餅', price: 65 },
          { name: '芋見乳酪烤餅', price: 65 },
        ],
        '☕ 現磨咖啡': [
          { name: '美式黑咖啡', price: 45 },
          { name: '特調咖啡', price: 45 },
          { name: '鮮乳拿鐵', price: 55 },
          { name: '蜜香美式', price: 60 },
          { name: '榛果風味拿鐵', price: 55 },
          { name: '焦糖風味拿鐵', price: 55 },
          { name: '蜜香拿鐵（大）', price: 65 },
          { name: '鯊魚拿鐵', price: 65 },
        ],
        '🧋 風味飲品': [
          { name: '紅茶（大）', price: 25 },
          { name: '招牌奶茶', price: 35, popular: true },
          { name: '非基改豆漿', price: 25 },
          { name: '鮮奶茶', price: 40 },
          { name: '台灣四季春', price: 40 },
          { name: '台灣四季春奶茶', price: 45 },
          { name: '豆漿紅茶', price: 40 },
          { name: '草莓牛奶', price: 50 },
          { name: '柚香四季春', price: 40 },
          { name: '阿華田', price: 45 },
          { name: '蘋果200冰茶', price: 50 },
          { name: '雲朵奶蓋紅茶', price: 50 },
          { name: '雲朵奶蓋青茶', price: 55 },
          { name: '芋見鮮奶（大）冰', price: 60 },
          { name: '芋見鮮奶（大）熱', price: 60 },
          { name: '鮮奶黑糖珍珠（冰）', price: 65 },
          { name: '鮮奶黑糖珍珠（熱）', price: 65 },
          { name: '巨峰葡萄風味氣泡飲（大）', price: 65 },
          { name: '青檸氣泡飲（大）', price: 65 },
          { name: '美梅氣泡飲', price: 65 },
        ],
      },
    },
    {
      id: 'maoshi',
      name: '卯時早午餐',
      badge: '4.9 ⭐ 高評價',
      address: '新北市五股區芳洲一路28號',
      hours: '07:00 - 13:00',
      menu: {
        '🍜 卯時炒麵': [
          { name: '碳烤雞腿炒麵', desc: '含煎蛋，獨門醬汁', price: 130, popular: true },
          { name: '辣味卡拉雞腿炒麵', desc: '含煎蛋', price: 130, popular: true },
          { name: '起司藍帶豬排炒麵', desc: '含煎蛋', price: 125 },
          { name: '厚切菲力雞排炒麵', desc: '含煎蛋', price: 125 },
          { name: '無骨黃金雞排炒麵', desc: '含煎蛋', price: 125, popular: true },
          { name: '酥炸大阪豬排炒麵', desc: '含煎蛋', price: 125 },
          { name: '香雞排炒麵', desc: '含煎蛋', price: 100 },
          { name: '黑胡椒豬排炒麵', desc: '含煎蛋', price: 110 },
          { name: '檸檬雞柳炒麵', desc: '含煎蛋', price: 110 },
          { name: '德式香腸炒麵', desc: '含煎蛋', price: 110 },
          { name: '招牌炒麵', desc: '含煎蛋', price: 75 },
        ],
        '🍝 風味炒麵': [
          { name: '咖喱烏龍麵', price: 70 },
          { name: '義大利肉醬麵', price: 70 },
          { name: '塔香三杯雞炒麵', price: 70 },
          { name: '宮保雞丁炒麵', price: 70 },
          { name: '泰式打拋豬炒麵', price: 70 },
        ],
        '🧀 乳酪餅': [
          { name: '果醬乳酪餅', price: 45 },
          { name: '起司乳酪餅', price: 50 },
          { name: '火腿乳酪餅', price: 55 },
          { name: '培根乳酪餅', price: 60 },
          { name: '大熱狗乳酪餅', price: 70 },
          { name: '檸檬雞柳乳酪餅', price: 75 },
        ],
        '🫓 手工酥皮蛋捲餅': [
          { name: '原味蛋捲餅', price: 40 },
          { name: '起司蛋捲餅', price: 50 },
          { name: '九層塔蛋捲餅', price: 55 },
          { name: '金黃玉米蛋捲餅', price: 60 },
          { name: '香酥培根蛋捲餅', price: 60 },
          { name: '火腿蛋捲餅', price: 50 },
          { name: '鮪魚蛋捲餅', price: 55 },
          { name: '巧克力起司蛋捲餅', price: 70 },
          { name: '香雞排蛋捲餅', price: 70 },
          { name: '香蒜乳酪蛋捲餅', price: 75 },
          { name: '火腿乳酪蛋捲餅', price: 75 },
          { name: '培根乳酪蛋捲餅', price: 75 },
          { name: '花生培根蛋捲餅', price: 80 },
          { name: '甲霸大熱狗蛋捲餅', price: 80 },
          { name: '玉米鮪魚蛋捲餅', price: 80 },
          { name: '起司薯餅蛋捲餅', price: 80 },
          { name: '檸檬雞柳蛋捲餅', price: 80 },
          { name: '塔香豬排蛋捲餅', price: 80 },
          { name: '起司三兄弟蛋捲餅', price: 85 },
          { name: '辣味卡拉雞腿蛋捲餅', price: 110 },
        ],
        '🍞 吐司 / 美式漢堡': [
          { name: '果醬薄片吐司', price: 30 },
          { name: '煎蛋', price: 45 },
          { name: '薯餅蛋', price: 50 },
          { name: '玉米蛋', price: 55 },
          { name: '鮪魚蛋', price: 55 },
          { name: '起司蛋', price: 55 },
          { name: '培根蛋', price: 55 },
          { name: '火腿蛋', price: 55 },
          { name: '香雞排蛋', price: 60 },
          { name: '豬排蛋', price: 60 },
          { name: '檸檬雞柳蛋', price: 75 },
          { name: '德式香腸起司蛋', price: 80 },
          { name: '起司藍帶豬排蛋', price: 90 },
          { name: '碳烤雞腿蛋', price: 95, popular: true },
          { name: '辣味卡拉雞腿蛋', price: 95 },
          { name: '無骨黃金雞排堡', price: 90 },
          { name: '起司藍帶豬排堡', price: 90 },
          { name: '厚切菲力雞排堡', price: 90 },
        ],
        '🥪 厚片': [
          { name: '果醬厚片', price: 50 },
          { name: '脆糖金沙厚片', price: 75 },
          { name: '培根玉米焗烤厚片', price: 85 },
          { name: '香蒜乳酪厚片', price: 80 },
          { name: '玉米鮪魚焗烤厚片', price: 85 },
          { name: '奶油火腿起司厚片', price: 80 },
          { name: '金沙乳酪厚片', price: 80 },
        ],
        '❣️ 單點小物': [
          { name: '古早味紅茶（附餐用）', price: 20 },
          { name: '甲霸大熱狗', price: 35 },
          { name: '原味美式小鬆餅', desc: '2片', price: 40, popular: true },
          { name: '雞柳條', desc: '兩支', price: 45 },
          { name: '小雞球', desc: '六顆', price: 45 },
          { name: '芋泥QQ', desc: '6顆', price: 45 },
          { name: '美式果醬小鬆餅', desc: '2片', price: 50 },
          { name: '炸餃', desc: '七入', price: 55 },
          { name: '酥炸雞軟骨', price: 55 },
          { name: '薯餅', desc: '兩片', price: 55 },
          { name: '辣味雞塊', desc: '五塊，椒麻口味', price: 60 },
          { name: '美式脆薯', price: 60 },
          { name: '黑糖起司饅頭', desc: '兩顆', price: 60 },
          { name: '辣味卡拉雞腿', price: 60 },
          { name: '碳烤雞腿', price: 60 },
          { name: '三杯蘿蔔糕', price: 65, popular: true },
          { name: '日式炒麵麵包', price: 85 },
          { name: '美式大熱狗堡', price: 80 },
          { name: '小熱狗', desc: '三條', price: 25 },
          { name: '蘿蔔糕', desc: '兩片', price: 50 },
          { name: '香雞排', price: 30 },
          { name: '黑胡椒豬排', price: 45 },
          { name: '無骨黃金雞排', price: 60 },
          { name: '嫩煎菲力雞排', price: 60 },
          { name: '起司藍帶豬排', price: 60 },
          { name: '酥炸豬排', price: 60 },
        ],
        '🥤 飲品': [
          { name: '古早味紅茶', price: 20 },
          { name: '美式咖啡', price: 40 },
          { name: '阿薩姆奶茶', price: 40 },
          { name: '豆漿', price: 40 },
          { name: '無糖豆漿', price: 40 },
          { name: '豆漿紅茶', price: 45 },
          { name: '豆漿奶茶', price: 45 },
          { name: '果汁牛奶', desc: '玻璃瓶裝', price: 45 },
          { name: '麥芽牛奶', desc: '玻璃瓶裝', price: 45 },
          { name: '草莓牛奶', desc: '玻璃瓶裝', price: 45 },
          { name: '巧克力牛奶', desc: '玻璃瓶裝', price: 45 },
          { name: '拿鐵咖啡', price: 50 },
          { name: '凍檸茶', price: 50, popular: true },
          { name: '紅茶鮮奶', price: 50 },
          { name: '鮮奶', price: 55 },
          { name: '黑糖鮮奶', price: 60 },
        ],
      },
    },
  ];
}
