import { Injectable, signal } from '@angular/core';
import { Store, MenuItem } from '../models/menu.model';

@Injectable({ providedIn: 'root' })
export class MenuDataService {
  private readonly _initialStores: Store[] = [
    {
      id: 'daily',
      name: '達利早餐',
      badge: '五股工商店',
      address: '新北市五股區工商路110號1樓',
      hours: '平日 06:00-13:30 / 假日 06:00-14:00',
      phone: '02-82927899',
      website: 'https://dailybreakfast.com.tw',
      menu: {
        '🌸 春果正當時': [
          { name: '蜜蘋肉桂滿分飽足餐', price: 124 },
          { name: '蜜蘋肉桂清爽升級餐', price: 85 },
          { name: '庄選香柚卡啦雞滿分飽足餐', price: 144 },
          { name: '庄選香柚卡啦雞清爽升級餐', price: 105 },
          { name: '旺來厚牛滿分飽足餐', price: 179 },
          { name: '旺來厚牛清爽升級餐', price: 140 },
          { name: '庄選香柚花園紅茶', price: 55 },
          { name: '100%蘋果紅茶', price: 65 },
        ],
        '🍽️ 達利集合': [
          { name: '(盤餐)英式圓餐包集合', price: 140 },
          { name: '(盤餐)鬆餅好時光集合', price: 150 },
          { name: '(盤餐)經典晨光集合', price: 155 },
          { name: '(盤餐)Here!鹽可頌集合', price: 155 },
          { name: '(盤餐)牛肉起司布里歐堡堡', price: 155 },
          { name: '(盤餐)檸檬優格魚排布里歐堡堡', price: 155 },
          { name: '(盤餐)經典法式雞腿集合', price: 160 },
          { name: '(盤餐)黑麥歐包集合', price: 160 },
        ],
        '🍱 經典食光餐': [
          { name: '招牌中式', price: 65 },
          { name: '小朋友最愛', price: 70 },
          { name: '眷村蝦米蔥拌麵', price: 78 },
          { name: '中式Double', price: 80 },
          { name: '蘑菇鐵板麵COMBO', price: 85 },
          { name: '黑胡椒鐵板麵COMBO', price: 85 },
          { name: '宮保雞丁鐵板麵COMBO', price: 95 },
        ],
        '🍔 布里歐漢堡': [
          { name: '漢堡肉堡', price: 45 },
          { name: '麥香雞堡', price: 45 },
          { name: '里肌豬排堡', price: 60 },
          { name: '蕈菇嫩蛋堡', price: 65 },
          { name: '檸檬優格魚排堡', price: 70 },
          { name: '經典牛肉起士堡', price: 70 },
          { name: '檸檬優格雞胸堡', price: 75 },
          { name: '蜜焰雞胸堡', price: 75 },
          { name: '蜜焰卡啦雞堡', price: 80 },
          { name: 'BBQ雞腿排堡', price: 80 },
          { name: '胡麻豬排堡', price: 85 },
          { name: '經典美式厚牛堡', price: 98 },
          { name: '黃金厚炸豬排堡', price: 85 },
        ],
        '🥪 半熟吐司': [
          { name: '方火腿吐司', price: 35 },
          { name: '漢堡肉吐司', price: 40 },
          { name: '麥香雞吐司', price: 40 },
          { name: '地瓜素鬆吐司', price: 45 },
          { name: '鮮蔬嫩蛋吐司', price: 45 },
          { name: '甜鮪魚吐司', price: 45 },
          { name: '里肌豬排吐司', price: 55 },
          { name: '經典蛋沙拉吐司', price: 55 },
          { name: '蔥蛋里肌吐司', price: 65 },
          { name: '檸檬優格魚排吐司', price: 65 },
          { name: '檸檬優格雞胸吐司', price: 70 },
          { name: '蜜焰香煎雞胸吐司', price: 70 },
        ],
        '🥙 半熟總匯': [
          { name: '總匯三明治', price: 75 },
          { name: '鮪魚蛋沙拉總匯', price: 75 },
          { name: '里肌總匯', price: 80 },
          { name: 'BBQ雞腿排總匯', price: 95 },
          { name: '花生蜜焰卡啦雞總匯', price: 98 },
        ],
        '🌯 墨西哥捲': [
          { name: '地瓜素鬆鮮蔬捲', price: 60 },
          { name: '檸檬優格雞胸捲', price: 85 },
          { name: '蜜焰卡啦雞捲', price: 85 },
          { name: '胡麻炸豬排捲', price: 85 },
          { name: '黃金厚切炸豬排捲', price: 85 },
        ],
        '🍞 果醬吐司': [
          { name: '美味草莓薄片', price: 25 },
          { name: '濃巧克力薄片', price: 25 },
          { name: '撲鼻香蒜薄片', price: 25 },
          { name: '香濃奶酥薄片', price: 25 },
          { name: '顆粒花生薄片', price: 25 },
        ],
        '🥖 果醬湯種厚片': [
          { name: '美味草莓厚片', price: 45 },
          { name: '濃巧克力厚片', price: 45 },
          { name: '撲鼻香蒜厚片', price: 45 },
          { name: '香濃奶酥厚片', price: 45 },
          { name: '顆粒花生厚片', price: 45 },
          { name: 'Oreo巧克力煉乳厚片', price: 55 },
        ],
        '🥚 蛋餅': [
          { name: '原味蛋餅', price: 30 },
          { name: '起士蛋餅', price: 40 },
          { name: '玉米蛋餅', price: 40 },
          { name: '火腿蛋餅', price: 45 },
          { name: '蔬菜蛋餅', price: 45 },
          { name: '厚蛋蔥香蛋餅', price: 50 },
          { name: '里肌豬排蛋餅', price: 55 },
          { name: '鮪魚蛋餅', price: 55 },
          { name: '拉絲蛋餅', price: 55 },
          { name: '薯餅起士蛋餅', price: 60 },
        ],
        '🍜 中式': [
          { name: '蔥抓餅', price: 40 },
          { name: '煎餃', price: 40 },
          { name: '蘿蔔糕', price: 45 },
          { name: '黑胡椒鐵板麵', price: 50 },
          { name: '蘑菇鐵板麵', price: 50 },
          { name: '宮保雞丁鐵板麵', price: 60 },
          { name: '達利炒麵', price: 65 },
        ],
        '🍝 義大利麵': [
          { name: '經典蕃茄肉醬義大利麵', price: 105 },
          { name: '義式青醬蕈菇義大利麵', price: 130 },
          { name: '奶油白醬蕈菇義大利麵', price: 130 },
          { name: '青醬蕈菇雞胸義大利麵', price: 150 },
          { name: '奶油蕈菇香煎雞腿義大利麵', price: 160 },
        ],
        '🍲 烏龍': [
          { name: '慢煮百菇湯烏龍', price: 120 },
          { name: '招牌和風湯烏龍', price: 135 },
          { name: '日式味噌湯烏龍', price: 145 },
          { name: '慢煮百菇炒烏龍', price: 110 },
          { name: '招牌和風炒烏龍', price: 120 },
          { name: '家傳椒麻炒烏龍', price: 125 },
          { name: '辣味噌炒烏龍', price: 135 },
        ],
        '🥗 水耕沙拉': [
          { name: '蛋沙拉水耕沙拉', price: 110 },
          { name: '牧場蕈菇水耕沙拉', price: 125 },
          { name: '嫩煎雞胸水耕沙拉', price: 130 },
          { name: '舒肥雞水耕沙拉', price: 158 },
        ],
        '🍚 達利碗': [
          { name: '晨光野菇達利碗', price: 145 },
          { name: '蔥鹽舒肥雞達利碗', price: 168 },
          { name: '泰香打拋達利碗', price: 168 },
          { name: '朝日厚切豬排達利碗', price: 175 },
        ],
        '🥐 鹽可頌': [
          { name: '地瓜火腿鹽可頌', price: 65 },
          { name: '蕈菇嫩蛋鹽可頌', price: 75 },
          { name: '鮮蝦蛋沙拉鹽可頌', price: 90 },
        ],
        '🥨 黑麥歐包': [
          { name: '地瓜火腿黑麥歐包', price: 65 },
          { name: '蕈菇嫩蛋黑麥歐包', price: 75 },
          { name: '鮮蝦蛋沙拉黑麥歐包', price: 90 },
        ],
        '🥟 小點': [
          { name: '荷包蛋', price: 15 },
          { name: '小熱狗', price: 20 },
          { name: '薯餅', price: 25 },
          { name: '鮮奶炒蛋', price: 35 },
          { name: '麥克雞塊', price: 38 },
          { name: '地瓜球', price: 40 },
          { name: '酥炸脆薯', price: 45 },
          { name: '(薯塔)薯餅起士蛋塔', price: 45 },
          { name: '蜜焰雞塊', price: 45 },
          { name: '檸檬優格雞柳', price: 50 },
        ],
        '🧇 麵包及鬆餅': [
          { name: '奶油餐包', price: 35 },
          { name: '蜂蜜法式吐司', price: 50 },
          { name: '鹽可頌', price: 45 },
          { name: '黑麥歐包', price: 45 },
          { name: '英式圓鬆餅', price: 50 },
          { name: '晨光厚片', price: 50 },
        ],
        '🥤 飲品': [
          { name: '紅茶', price: 20 },
          { name: '無糖綠茶', price: 20 },
          { name: '達利奶茶', price: 30 },
          { name: '鮮檸檬紅茶', price: 25 },
          { name: '豆漿', price: 25 },
          { name: '豆奶紅茶', price: 25 },
          { name: '鮮奶茶', price: 35 },
          { name: '經典可可', price: 45 },
          { name: '鮮奶', price: 45 },
          { name: '花園奶茶', price: 45 },
          { name: '花園鮮奶茶', price: 50 },
          { name: '香蜜鮮奶茶', price: 45 },
          { name: '蜂釀牛奶', price: 50 },
          { name: '天然柳橙原汁', price: 65 },
          { name: '奇異果綜合汁', price: 65 },
        ],
        '☕ 咖啡': [
          { name: '美式咖啡', price: 35 },
          { name: '春蜜美式', price: 45 },
          { name: '特調咖啡', price: 45 },
          { name: '招牌拿鐵', price: 50 },
          { name: '焦糖拿鐵', price: 60 },
          { name: '榛果拿鐵', price: 60 },
          { name: '春蜜拿鐵', price: 60 },
        ],
      },
    },
    {
      id: 'mwd',
      name: '麥味登',
      badge: '五股中興店',
      address: '新北市五股區中興路四段48巷1號1樓',
      hours: '06:30 - 15:30',
      phone: '+886922511853',
      menu: {
        '🍔 漢堡': [
          { name: '超厚牛肉起司漢堡', price: 90 },
          { name: '香雞漢堡', price: 45 },
          { name: '豬肉漢堡', price: 50 },
          { name: '超厚雞肉起司漢堡', price: 85 },
          { name: '培根漢堡', price: 55 },
          { name: '黑胡椒豬里肌漢堡', price: 60 },
          { name: '鮪魚漢堡', price: 55 },
          { name: '燻雞漢堡', price: 55 },
          { name: '鮮蛋沙拉漢堡', price: 50 },
          { name: '歐姆蛋漢堡', price: 55 },
          { name: '鮮蔬漢堡', price: 50 },
          { name: '卡滋雞腿漢堡', price: 85 },
          { name: '原塊嫩雞起司漢堡', price: 105 },
        ],
        '🍞 湯種': [
          { name: '超厚牛肉起司湯種', price: 90 },
          { name: '卡滋雞腿湯種', price: 85 },
          { name: '燻雞湯種', price: 55 },
          { name: '黑胡椒豬里肌湯種', price: 60 },
          { name: '鮪魚湯種', price: 55 },
          { name: '歐姆蛋湯種', price: 55 },
          { name: '鮮蛋沙拉湯種', price: 50 },
          { name: '培根湯種', price: 55 },
          { name: '香雞湯種', price: 45 },
          { name: '豬肉湯種', price: 50 },
          { name: '超厚雞肉起司湯種', price: 85 },
          { name: '鮮蔬湯種', price: 50 },
          { name: '原塊嫩雞起司湯種', price: 105 },
        ],
        '🧇 滿分堡': [
          { name: '超厚雞肉起司滿分堡', price: 75 },
          { name: '原塊嫩雞起司滿分堡', price: 95 },
          { name: '黑胡椒豬里肌蛋滿分堡', price: 70 },
          { name: '火腿薯餅滿分堡', price: 55 },
          { name: '歐姆蛋滿分堡', price: 55 },
          { name: '鮪魚蛋滿分堡', price: 70 },
          { name: '豬肉起司滿分堡', price: 60 },
          { name: '花生厚牛起司滿分堡', price: 90 },
        ],
        '🥨 經典丹麥麵包': [
          { name: '卡滋雞腿丹麥麵包', price: 100 },
          { name: '超厚牛肉起司丹麥麵包', price: 105 },
          { name: '鮮蛋沙拉丹麥麵包', price: 70 },
          { name: '鮪魚丹麥麵包', price: 75 },
          { name: '香雞丹麥麵包', price: 60 },
          { name: '超厚雞肉起司丹麥麵包', price: 100 },
          { name: '燻雞丹麥麵包', price: 75 },
          { name: '黑胡椒豬里肌丹麥麵包', price: 85 },
          { name: '培根丹麥麵包', price: 75 },
          { name: '鮮蔬丹麥麵包', price: 70 },
          { name: '豬肉丹麥麵包', price: 70 },
          { name: '歐姆蛋丹麥麵包', price: 75 },
          { name: '原塊嫩雞起司丹麥', price: 120 },
        ],
        '🥐 經典可頌麵包': [
          { name: '卡滋雞腿可頌', price: 100 },
          { name: '燻雞可頌', price: 75 },
          { name: '鮪魚可頌', price: 75 },
          { name: '超厚牛肉起司可頌', price: 105 },
          { name: '鮮蛋沙拉可頌', price: 70 },
          { name: '香雞可頌', price: 60 },
          { name: '培根可頌', price: 75 },
          { name: '黑胡椒豬里肌可頌', price: 85 },
          { name: '豬肉可頌', price: 70 },
          { name: '歐姆蛋可頌', price: 75 },
          { name: '鮮蔬可頌', price: 70 },
          { name: '超厚雞肉起司可頌', price: 100 },
          { name: '原塊嫩雞起司可頌', price: 120 },
        ],
        '🍳 早午餐': [
          { name: '美式鬆餅特餐', price: 140 },
          { name: '法式蘿勒鮪魚特餐', price: 170 },
          { name: '幸福特餐', price: 150 },
          { name: '好食嫩雞餐', price: 205 },
          { name: '法式特餐', price: 150 },
          { name: '泰式卡滋脆雞特餐', price: 205 },
          { name: '樂活特餐', price: 160 },
          { name: '威爾遜嫩煎腿排可頌餐', price: 210 },
          { name: '蘿勒燻雞三明治特餐', price: 165 },
          { name: '台式特餐', price: 170 },
        ],
        '👨‍🍳 主廚': [
          { name: '奶油培根義大利麵', price: 145 },
          { name: '茄汁原塊嫩雞義大利麵', price: 170 },
          { name: '青醬雞肉義大利麵', price: 160 },
          { name: '西式紅酒牛肉飯', price: 250 },
          { name: '青醬蘑菇義大利麵', price: 160 },
          { name: '茄汁德腸燉飯', price: 170 },
          { name: '蘿勒燻雞燉飯', price: 170 },
          { name: '咖哩唐揚雞蛋包飯', price: 195 },
        ],
        '🍜 中式': [
          { name: '黃金泡菜酥炸餃', price: 55 },
          { name: '手工蔥抓蛋餅', price: 55 },
          { name: '蘑菇鐵板麵', price: 60 },
          { name: '黑胡椒鐵板麵', price: 60 },
          { name: '黃金泡菜蘿蔔糕', price: 60 },
          { name: '鮪魚蛋餅', price: 60 },
          { name: '薯餅蛋餅', price: 60 },
          { name: '德腸握蛋捲餅', price: 85 },
          { name: '豬里肌握蛋捲餅', price: 85 },
          { name: '培根蛋餅', price: 70 },
          { name: '燻雞握蛋捲餅', price: 85 },
          { name: '豬里肌蛋餅', price: 70 },
          { name: '培根握蛋捲餅', price: 85 },
          { name: '鮪魚握蛋捲餅', price: 85 },
          { name: '蘿蔔糕', price: 45 },
          { name: '起司雙重奏握蛋捲餅', price: 85 },
          { name: '眷村麻醬鐵板麵(含蛋)', price: 70 },
          { name: '中式拼盤', price: 85 },
          { name: '古早味拼盤', price: 90 },
          { name: '原味蛋餅', price: 40 },
          { name: '川味麻辣鐵板麵(含蛋)', price: 70 },
        ],
        '🥗 輕食尚餐': [
          { name: '地瓜雞肉餐', price: 190 },
          { name: '優蛋白蛋捲餐', price: 180 },
          { name: '紫米時蔬嫩雞飯', price: 170 },
        ],
        '🥟 點心': [
          { name: '雞塊', price: 50 },
          { name: '薯餅蛋塔', price: 55 },
          { name: '黃金脆薯', price: 50 },
          { name: '法國吐司', price: 45 },
          { name: '四角薯餅', price: 50 },
          { name: '椒麻雞塊', price: 60 },
          { name: '香檸雞柳', price: 50 },
          { name: '美式鬆餅', price: 50 },
          { name: '時蔬嫩蛋', price: 60 },
          { name: '嫩煎雞腿排', price: 80 },
          { name: '唐揚雞塊', price: 85 },
          { name: '歐姆蛋', price: 50 },
          { name: '台灣番薯', price: 55 },
          { name: '菜脯蛋', price: 35 },
          { name: '原塊嫩雞(單片)', price: 80 },
        ],
        '🧋 飲料': [
          { name: '冰奶茶大杯', price: 40 },
          { name: '冰奶茶特大杯', price: 45 },
          { name: '冰紅茶大杯', price: 35 },
          { name: '冰紅茶特大杯', price: 40 },
          { name: '冰紅茶拿鐵', price: 45 },
          { name: '冰可可牛乳', price: 50 },
          { name: '熱紅茶拿鐵', price: 45 },
          { name: '熱奶茶大杯', price: 40 },
          { name: '熱紅茶大杯', price: 35 },
          { name: '冰綠茶特大杯', price: 40 },
          { name: '夏威夷冰茶', price: 60 },
          { name: '冰綠茶大杯', price: 35 },
          { name: '冰山藥薏仁', price: 50 },
          { name: '手熬冬瓜茶', price: 50 },
          { name: '熱奶茶特大杯', price: 45 },
          { name: '熱帶水果茶', price: 60 },
          { name: '冰紐西蘭牛奶', price: 55 },
          { name: '萊姆蜜紅茶', price: 60 },
          { name: '熱山藥薏仁', price: 50 },
          { name: '鮮檸冬瓜茶', price: 60 },
          { name: '熱可可牛乳', price: 50 },
          { name: '熱紅茶特大杯', price: 40 },
          { name: '熱紐西蘭牛奶', price: 55 },
          { name: '豆漿紅茶(L)(冰)', price: 35 },
          { name: '豆漿紅茶(L)(熱)', price: 35 },
          { name: '豆漿紅茶(XL)(冰)', price: 40 },
          { name: '豆漿紅茶(XL)(熱)', price: 40 },
          { name: '無糖豆漿(L)(冰)', price: 35 },
          { name: '無糖豆漿(L)(熱)', price: 35 },
          { name: '無糖豆漿(XL)(冰)', price: 40 },
          { name: '無糖豆漿(XL)(熱)', price: 40 },
          { name: '黑糖方Q撞奶(冰)(', price: 80 },
        ],
        '☕ 咖啡': [
          { name: '冰拿鐵咖啡', price: 65 },
          { name: '冰美式咖啡', price: 55 },
          { name: '熱拿鐵咖啡', price: 65 },
          { name: '冰焦糖拿鐵咖啡', price: 75 },
          { name: '熱美式咖啡', price: 55 },
          { name: '冰榛果拿鐵咖啡', price: 75 },
          { name: '熱焦糖拿鐵咖啡', price: 75 },
          { name: '熱榛果拿鐵咖啡', price: 75 },
        ],
        '🍓 湯種果醬': [
          { name: '巧克力湯種', price: 35 },
          { name: '草莓湯種', price: 35 },
          { name: '巧克力丹麥', price: 50 },
          { name: '顆粒花生湯種', price: 35 },
          { name: '巧克力布里歐皇厚吐司', price: 50 },
          { name: '顆粒花生布里歐皇厚吐司', price: 50 },
          { name: '香蒜湯種', price: 35 },
          { name: '香蒜布里歐皇厚吐司', price: 50 },
          { name: '顆粒花生丹麥', price: 50 },
          { name: '香蒜丹麥', price: 50 },
          { name: '草莓布里歐皇厚吐司', price: 50 },
          { name: '草莓丹麥', price: 50 },
          { name: '奶酥湯種', price: 35 },
          { name: '奶酥丹麥', price: 50 },
          { name: '奶酥布里歐皇厚吐司', price: 50 },
        ],
        '🍲 湯品及沙拉': [
          { name: '巧達濃湯', price: 55 },
          { name: '奶油玉米濃湯', price: 40 },
        ],
      },
    },
    {
      id: 'qburger',
      name: 'Q Burger',
      badge: '五股國小店',
      address: '新北市五股區成泰路二段108號',
      hours: '06:00 - 14:00',
      website: 'https://www.qburger.com.tw',
      menu: {
        '✨ 期間限定': [
          { name: '【套餐】吳寶春 · 鮮蔬莫扎瑞拉火腿佛卡夏', price: 213 },
          { name: '【套餐】吳寶春 · 鮮蔬莫扎瑞拉鮪魚佛卡夏', price: 213 },
          { name: '【套餐】吳寶春 · 鮮蔬橙香米蘭豬排佛卡夏', price: 246 },
          { name: '【套餐】吳寶春佛卡夏·鮮蔬莫札瑞拉德式香腸餐', price: 233 },
          { name: '【套餐】嫩蛋卡啦雞佛卡夏· 鮮蔬莫扎瑞拉餐', price: 246 },
          { name: '【套餐】雙倍嫩蛋佛卡夏· 鮮蔬莫扎瑞拉餐', price: 206 },
          { name: '【套餐】鮮蔬莫扎瑞拉起士吐司', price: 112 },
          { name: '【套餐】鮮蔬莫扎瑞拉火腿吐司', price: 133 },
          { name: '【套餐】米蘭豬排起士白醬燉飯', price: 259 },
          { name: '【套餐】培根雞肉捲紅醬義大利麵', price: 246 },
          { name: '氣泡冰咖啡(大)', price: 91 },
          { name: '西西里氣泡冰咖啡(大)', price: 111 },
          { name: '【必喝推薦】鯊魚拿鐵-冰(8oz)', price: 91 },
          { name: '巨峰葡萄風味氣泡飲', price: 85 },
          { name: '青檸氣泡飲', price: 85 },
          { name: '太妃焦糖風味鮮奶茶(中)冰', price: 78 },
          { name: '太妃焦糖風味鮮奶茶(中)熱', price: 78 },
          { name: '美梅氣泡飲', price: 85 },
          { name: 'Q梅青茶(特大)', price: 78 },
          { name: 'Q梅青茶(大)', price: 65 },
        ],
        '🥯 可芮絲': [
          { name: '【單點】可芮絲蜂蜜可朗芙', price: 126 },
          { name: '【單點】可芮絲經典可朗芙', price: 120 },
        ],
        '🥪 吐司': [
          { name: '【套餐】燒肉蛋吐司', price: 120 },
          { name: '【套餐】燒肉乳酪蛋吐司', price: 140 },
          { name: '【套餐】經典火腿蛋吐司', price: 98 },
          { name: '【套餐】里肌豬排吐司', price: 113 },
          { name: '【套餐】100%肉鬆花生蛋吐司', price: 120 },
          { name: '【套餐】鮪魚吐司', price: 100 },
          { name: '【套餐】培根蛋吐司', price: 120 },
          { name: '【套餐】薯餅起士吐司', price: 106 },
          { name: '【套餐】嫩脆雞胸吐司', price: 133 },
          { name: '【套餐】鮮蔬蕃茄起士吐司', price: 93 },
          { name: '【套餐】鮮蔬馬鈴薯沙拉吐司', price: 93 },
          { name: '【套餐】里肌豬排總匯', price: 160 },
          { name: '巧克力吐司', price: 33 },
          { name: '【單點】巧克力厚片', price: 53 },
          { name: '【單點】花生吐司', price: 33 },
          { name: '【單點】花生厚片', price: 53 },
          { name: '【單點】草莓吐司', price: 33 },
          { name: '【單點】草莓厚片', price: 53 },
          { name: '【單點】奶油吐司', price: 33 },
          { name: '【單點】奶油厚片', price: 53 },
          { name: '【單點】椰香吐司', price: 33 },
          { name: '【單點】椰香厚片', price: 53 },
        ],
        '🍔 漢堡': [
          { name: '【套餐】花生熔岩卡啦雞腿堡(辣)', price: 153 },
          { name: '【套餐】嫩脆雞胸堡', price: 140 },
          { name: '【套餐】里肌豬排堡', price: 120 },
          { name: '【套餐】卡啦雞腿堡', price: 140 },
          { name: '【套餐】經典牛肉起士堡', price: 152 },
          { name: '【套餐】牛肉起士堡', price: 133 },
          { name: '【套餐】阿拉斯加鱈魚堡', price: 140 },
          { name: '【套餐】蜜汁嫩雞腿堡', price: 146 },
          { name: '【單點】花生熔岩卡啦雞腿堡(辣)', price: 120 },
        ],
        '🥖 起士軟法': [
          { name: '【套餐】鮪魚起士軟法', price: 140 },
          { name: '【套餐】嫩脆雞胸起士軟法', price: 165 },
          { name: '【套餐】阿拉斯加鱈魚起士軟法', price: 160 },
        ],
        '🥚 蛋餅&蔥抓餅': [
          { name: '【套餐】怪怪總匯蛋餅', price: 133 },
          { name: '【套餐】玉米蛋餅', price: 93 },
          { name: '【套餐】培根蛋餅', price: 113 },
          { name: '【套餐】九層塔蛋餅', price: 93 },
          { name: '【套餐】100%肉鬆蛋餅', price: 113 },
          { name: '【套餐】里肌豬排蛋餅', price: 120 },
          { name: '【套餐】原味蔥抓餅', price: 86 },
          { name: '【套餐】里肌豬排蔥抓餅', price: 133 },
        ],
        '🍝 炒泡麵&鐵板麵': [
          { name: '【套餐】招牌炒泡麵經典組合', price: 173 },
          { name: '【套餐】椒麻炒泡麵經典組合', price: 180 },
          { name: '【套餐】招牌炒泡麵', price: 113 },
          { name: '【套餐】椒麻炒泡麵', price: 120 },
          { name: '【套餐】黑胡椒鐵板麵經典組合', price: 166 },
          { name: '【套餐】蘑菇鐵板麵經典組合', price: 166 },
          { name: '【套餐】沙茶鐵板麵經典組合', price: 166 },
          { name: '【套餐】黑胡椒鐵板麵', price: 106 },
          { name: '【套餐】蘑菇鐵板麵', price: 106 },
          { name: '【套餐】沙茶鐵板麵', price: 106 },
          { name: '【單點】招牌炒泡麵經典組合', price: 140 },
          { name: '【單點】沙茶鐵板麵經典組合', price: 133 },
          { name: '【單點】蘑菇鐵板麵經典組合', price: 133 },
        ],
        '🍜 鍋燒麵': [
          { name: '【套餐】里肌豬排鍋燒麵-意麵', price: 180 },
          { name: '【套餐】里肌豬排鍋燒麵-烏龍麵', price: 180 },
          { name: '【套餐】里肌豬排鍋燒麵-泡麵', price: 186 },
          { name: '【套餐】沙茶里肌豬排鍋燒麵-意麵', price: 193 },
          { name: '【套餐】沙茶里肌豬排鍋燒麵-烏龍麵', price: 193 },
          { name: '【套餐】沙茶里肌豬排鍋燒麵-泡麵', price: 200 },
        ],
        '🍳 經典盤餐': [
          { name: '【套餐】QB經典大滿足', price: 239 },
          { name: '【套餐】中式組合餐', price: 126 },
          { name: '【套餐】歡樂兒童餐', price: 126 },
          { name: '【套餐】里肌豬總匯盤餐', price: 193 },
          { name: '【套餐】鮪魚玉米可朗芙盤餐', price: 200 },
          { name: '【套餐】蜂蜜芥末卡啦雞可朗芙盤餐', price: 239 },
        ],
        '🍟 快樂小食光': [
          { name: '【套餐】兒童餐 (蘿蔔糕+雞塊+蔬果杯)', price: 126 },
          { name: '【套餐】兒童餐 (蘿蔔糕+熱狗+蔬果杯)', price: 126 },
          { name: '【套餐】兒童餐 (薯條+雞塊+蔬果杯)', price: 126 },
          { name: '【套餐】兒童餐 (薯條+熱狗+蔬果杯)', price: 126 },
          { name: '【套餐】兒童餐 (草莓吐司+雞塊+蔬果杯)', price: 126 },
          { name: '【套餐】兒童餐 (草莓吐司+熱狗+蔬果杯)', price: 126 },
        ],
        '🥐 可朗芙': [
          { name: '【單點】鮪魚玉米可朗芙', price: 106 },
          { name: '【單點】起士嫩蛋可朗芙', price: 106 },
          { name: '【單點】蜂蜜芥末卡啦雞可朗芙', price: 146 },
          { name: '【單點】雙重巧克可朗芙', price: 93 },
          { name: '【單點】蜂蜜可朗芙', price: 80 },
          { name: '【單點】草莓煉乳可朗芙', price: 93 },
          { name: '【單點】經典可朗芙', price: 73 },
          { name: '【單點】花醬可朗芙', price: 86 },
          { name: '【單點】香蘋煉乳可朗芙', price: 93 },
        ],
        '🧇 烤餅': [
          { name: '【單點】花生乳酪烤餅', price: 67 },
          { name: '【單點】瑪格麗特烤餅', price: 93 },
          { name: '【單點】夏威夷烤餅', price: 93 },
        ],
        '🌯 墨西哥捲': [
          { name: '【套餐】嫩脆雞胸墨西哥捲', price: 146 },
          { name: '【套餐】德式香腸墨西哥捲', price: 133 },
          { name: '【套餐】蜜汁嫩雞腿墨西哥捲', price: 153 },
          { name: '【套餐】卡啦雞腿墨西哥捲', price: 146 },
          { name: '【套餐】田園蔬菜墨西哥捲', price: 106 },
        ],
        '🥗 輕享新食尚': [
          { name: '【單點】蜜汁烤雞腿嫩炒蛋餐(千島醬)', price: 219 },
          { name: '【單點】蜜汁烤雞腿嫩炒蛋餐(和風醬)', price: 219 },
          { name: '【單點】菲力雞嫩炒蛋餐(千島醬)', price: 213 },
          { name: '【單點】菲力雞嫩炒蛋餐(和風醬)', price: 213 },
          { name: '【單點】香煎嫩雞大沙拉(千島醬)', price: 153 },
          { name: '【單點】香煎嫩雞大沙拉 (和風醬)', price: 153 },
          { name: '【單點】香蘋鮮蔬沙拉(千島醬)', price: 93 },
          { name: '【單點】香蘋鮮蔬沙拉(和風醬)', price: 93 },
          { name: '【單點】鮮蔬沙拉(千島醬)', price: 73 },
          { name: '【單點】鮮蔬沙拉(和風醬)', price: 73 },
        ],
        '🍚 義大利麵&燉飯': [
          { name: '【套餐】奶香培根義大利麵', price: 180 },
          { name: '【套餐】奶香鮪魚義大利麵', price: 186 },
          { name: '【套餐】拿坡里蕃茄德腸乳酪義大利麵', price: 193 },
          { name: '【單點】奶香培根義大利麵', price: 146 },
          { name: '【單點】拿坡里蕃茄德腸乳酪義大利麵', price: 160 },
        ],
        '☕ 風味飲品&現磨咖啡': [
          { name: '焦糖風味拿鐵(中)-冰', price: 85 },
          { name: '焦糖風味拿鐵(中)-熱', price: 85 },
          { name: '美式黑咖啡(中)', price: 52 },
          { name: '美式黑咖啡(大)', price: 65 },
          { name: '美式黑咖啡(特大)', price: 85 },
          { name: '特調咖啡(中)', price: 58 },
          { name: '特調咖啡(大)', price: 72 },
          { name: '特調咖啡(特大)', price: 91 },
          { name: '鮮乳拿鐵(中)-冰', price: 65 },
          { name: '鮮乳拿鐵(中)-熱', price: 65 },
          { name: '鮮乳拿鐵(大)-冰', price: 78 },
          { name: '鮮乳拿鐵(大)-熱', price: 78 },
          { name: '鮮乳拿鐵(特大)-冰', price: 98 },
          { name: '鮮乳拿鐵(特大)-熱', price: 98 },
          { name: '榛果風味拿鐵(中)-冰', price: 85 },
          { name: '榛果風味拿鐵(中)-熱', price: 85 },
          { name: '經典紅茶(中)', price: 32 },
          { name: '經典紅茶(大)', price: 38 },
          { name: '經典紅茶(特大)', price: 45 },
          { name: '招牌奶茶(中)', price: 38 },
          { name: '招牌奶茶(大)', price: 45 },
          { name: '招牌奶茶(特大)', price: 52 },
          { name: '【鮮奶淡定】單點-鮮奶茶(中)', price: 58 },
          { name: '鮮奶茶(大)', price: 65 },
          { name: '鮮奶茶(特大)', price: 78 },
          { name: '阿華田(中)', price: 58 },
          { name: '阿華田(大)', price: 65 },
          { name: '台灣四季春-冰(大)', price: 52 },
          { name: '台灣四季春-熱 (大)', price: 52 },
          { name: '台灣四季春-冰(特大)', price: 58 },
          { name: '台灣四季春-熱 (特大)', price: 58 },
          { name: '台灣四季春奶茶(大)-冰', price: 58 },
          { name: '台灣四季春奶茶(大)-熱', price: 58 },
          { name: '台灣四季春奶茶(特大)-冰', price: 65 },
          { name: '台灣四季春奶茶(特大)-熱', price: 65 },
          { name: '非基改豆漿(中)', price: 38 },
          { name: '非基改豆漿(中)半糖', price: 38 },
          { name: '非基改豆漿(中)無糖', price: 38 },
          { name: '非基改豆漿(大)', price: 45 },
          { name: '非基改豆漿(大)半糖', price: 45 },
          { name: '非基改豆漿(大)無糖', price: 45 },
          { name: '豆漿紅茶 -冰(大)', price: 45 },
          { name: '豆漿紅茶 -熱(大)', price: 45 },
          { name: '豆漿紅茶 -冰(特大)', price: 52 },
          { name: '豆漿紅茶 -熱(特大)', price: 52 },
          { name: '雲朵奶蓋紅茶(大', price: 65 },
          { name: '雲朵奶蓋紅茶(特大', price: 72 },
          { name: '雲朵奶蓋青茶(大', price: 78 },
          { name: '雲朵奶蓋青茶(特大', price: 85 },
        ],
        '🥟 點心': [
          { name: '金牌蘿蔔糕', price: 60 },
          { name: '薯餅起士蛋塔', price: 73 },
          { name: 'QQ地瓜球', price: 53 },
          { name: '經典香蔥脆薯', price: 67 },
          { name: '麥克雞塊(4塊)-附糖醋醬', price: 60 },
          { name: '熱狗', price: 40 },
          { name: '薯餅', price: 40 },
          { name: '德式香腸', price: 60 },
          { name: '雞米花', price: 67 },
        ],
        '🍽️ 單點': [
          { name: '【單點】里肌豬排蛋餅', price: 86 },
          { name: '【單點】玉米蛋餅', price: 60 },
          { name: '【單點】鮪魚蛋餅', price: 80 },
          { name: '【單點】怪怪總匯蛋餅', price: 100 },
          { name: '【單點】原味蔥抓餅', price: 53 },
          { name: '【單點】100%肉鬆花生蛋吐司', price: 86 },
          { name: '【單點】嫩脆雞胸堡', price: 106 },
          { name: '【單點】牛肉起士堡', price: 100 },
          { name: '【單點】卡啦雞腿堡', price: 106 },
          { name: '【單點】鮪魚吐司', price: 67 },
        ],
      },
    },
    {
      id: 'maoshi',
      name: '卯時早午餐',
      badge: '4.9 ⭐ 高評價',
      address: '新北市五股區芳洲一路28號',
      hours: '07:00 - 13:00',
      phone: '+886282921860',
      menu: {
        '🍝 卯時炒麵': [
          { name: '無骨黃金雞排炒麵', price: 125 },
          { name: '起司藍帶豬排炒麵', price: 125 },
          { name: '招牌炒麵', price: 75 },
          { name: '辣味卡拉雞腿炒麵', price: 130 },
          { name: '厚切菲力雞排炒麵', price: 125 },
          { name: '酥炸大阪豬排炒麵', price: 125 },
          { name: '香雞排炒麵', price: 100 },
          { name: '豬排炒麵', price: 110 },
          { name: '檸檬雞柳炒麵', price: 110 },
          { name: '德式香腸炒麵', price: 110 },
        ],
        '🍝 風味炒麵': [
          { name: '咖喱烏龍麵', price: 70 },
          { name: '番茄肉醬義大利麵', price: 70 },
          { name: '塔香三杯雞炒麵', price: 70 },
          { name: '宮保雞丁炒麵', price: 70 },
          { name: '泰式打拋豬炒麵', price: 70 },
        ],
        '✨ 新品上市': [
          { name: '日式炒麵麵包', price: 85 },
          { name: '美式大熱狗堡', price: 80 },
        ],
        '🍔 卯時吐司/漢堡': [
          { name: '辣味卡拉雞腿蛋', price: 95 },
          { name: '四盎司起司牛肉蛋', price: 120 },
          { name: '香雞排蛋', price: 60 },
          { name: '鮪魚蛋', price: 60 },
          { name: '火腿蛋', price: 55 },
          { name: '豬排蛋', price: 65 },
          { name: '起司藍帶豬排蛋', price: 90 },
          { name: '培根蛋', price: 55 },
          { name: '四盎司培根牛肉蛋', price: 130 },
          { name: '薯餅蛋', price: 60 },
          { name: '檸檬雞柳蛋', price: 75 },
          { name: '德式香腸起司蛋', price: 80 },
          { name: '果醬吐司', price: 30 },
          { name: '煎蛋', price: 45 },
          { name: '起司蛋', price: 55 },
          { name: '玉米蛋', price: 55 },
        ],
        '🧇 厚片系列': [
          { name: '果醬厚片', price: 50 },
          { name: '玉米鮪魚焗烤厚片', price: 85 },
          { name: '培根玉米焗烤厚片', price: 85 },
          { name: '金沙乳酪厚片', price: 80 },
        ],
        '🥚 手工酥皮蛋捲餅': [
          { name: '金黃玉米蛋捲餅', price: 55 },
          { name: '香酥培根蛋捲餅', price: 55 },
          { name: '玉米鮪魚蛋捲餅', price: 65 },
          { name: '起司薯餅蛋捲餅', price: 70 },
          { name: '甲霸大熱狗蛋捲餅', price: 60 },
          { name: '塔香豬排蛋捲餅', price: 70 },
          { name: '起司蛋捲餅', price: 50 },
          { name: '起司三兄弟蛋捲餅', price: 70 },
          { name: '辣味卡拉雞腿蛋捲餅', price: 95 },
          { name: '花生培根蛋捲餅', price: 70 },
          { name: '培根乳酪蛋捲餅', price: 65 },
          { name: '九層塔蛋捲餅', price: 50 },
          { name: '火腿乳酪蛋捲餅', price: 60 },
          { name: '香雞排蛋捲餅', price: 60 },
          { name: '韓式泡菜蛋捲餅', price: 65 },
          { name: '巧克力起司蛋捲餅', price: 55 },
          { name: '檸檬雞柳蛋餅蛋捲餅', price: 75 },
        ],
        '🍽️ 卯時單品': [
          { name: '三杯蘿蔔糕', price: 65 },
          { name: '小熱狗', price: 25 },
          { name: '蘿蔔糕', price: 50 },
          { name: '炸餃', price: 55 },
          { name: '薯餅', price: 55 },
          { name: '無骨黃金雞排', price: 60 },
          { name: '香雞排', price: 30 },
          { name: '辣味雞塊', price: 60 },
          { name: '小雞球', price: 45 },
          { name: '美式脆薯', price: 60 },
          { name: '甲霸大熱狗', price: 35 },
          { name: '芋泥球', price: 45 },
          { name: '雞柳條', price: 45 },
          { name: '辣味卡拉雞腿', price: 60 },
          { name: '起司藍帶豬排', price: 60 },
          { name: '黑胡椒豬排', price: 45 },
        ],
        '🧀 乳酪餅': [
          { name: '果醬乳酪餅', price: 45 },
          { name: '起司乳酪餅', price: 50 },
          { name: '火腿乳酪餅', price: 50 },
          { name: '培根乳酪餅', price: 55 },
          { name: '大熱狗乳酪餅', price: 65 },
          { name: '檸檬雞柳乳酪餅', price: 75 },
        ],
        '🧋 飲料': [
          { name: '阿薩姆奶茶', price: 40 },
          { name: '豆漿', price: 40 },
          { name: '凍檸茶', price: 50 },
          { name: '古早味紅茶', price: 25 },
          { name: '美式咖啡【冰/熱】', price: 40 },
          { name: '豆漿紅茶', price: 45 },
          { name: '草莓牛奶', price: 45 },
          { name: '巧克力牛奶', price: 45 },
          { name: '豆漿奶茶', price: 45 },
          { name: '果汁牛奶', price: 45 },
          { name: '麥芽牛奶', price: 45 },
          { name: '無糖豆漿', price: 40 },
        ],
      },
    },
  ];

  private readonly _stores = signal<Store[]>(this._initialStores);
  readonly stores = this._stores.asReadonly();

  addStore(store: Store): void {
    this._stores.update(s => [...s, store]);
  }

  updateStoreMenu(storeId: string, menu: Record<string, MenuItem[]>): void {
    this._stores.update(stores =>
      stores.map(s => s.id === storeId ? { ...s, menu } : s)
    );
  }
}
